import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.functionName = "downloadPoster"
end sub

sub downloadPoster()
    itemId = m.top.itemId
    imageType = m.top.imageType
    imageUrl = m.top.imageUrl

    if not isValidAndNotEmpty(itemId) or not isValidAndNotEmpty(imageUrl)
        m.top.result = { success: false }
        return
    end if

    success = api.items.DownloadRemoteImages(itemId, imageType, imageUrl)
    m.top.result = { success: success }
end sub
