import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.functionName = "fetchRemoteImages"
end sub

sub fetchRemoteImages()
    itemId = m.top.itemId
    imageType = m.top.imageType

    if not isValidAndNotEmpty(itemId)
        m.top.images = { success: false, items: [] }
        return
    end if

    params = {
        "type": imageType,
        "limit": 30
    }

    data = api.items.GetRemoteImages(itemId, params)

    if not isValid(data) or not isValid(data.Images)
        m.top.images = { success: false, items: [] }
        return
    end if

    m.top.images = { success: true, items: data.Images }
end sub
