function Request(url as string, method = "GET" as string, body = "" as string, headers = {} as object, honorCancellation = true as boolean) as object
    m.requests.Push({ url: url, method: method, body: body, headers: headers })
    if m.responses.Count() = 0 then return { status: 0, data: invalid }
    response = m.responses.Shift()
    if m.cancelAfterRequest = m.requests.Count() then m.top.cancelRequested = true
    return response
end function
