import "pkg:/source/api/EmbyConnect.bs"

sub init()
    m.top.functionName = "execute"
end sub

sub execute()
    result = { error: "network" }
    try
        if m.top.mode = "authenticate"
            result = embyConnect.Authenticate(m.top.username, m.top.password)
        else
            result = embyConnect.Exchange(m.top.server, m.top.connectUserId)
        end if
    catch error
        result = { error: "response" }
    end try
    m.top.password = ""
    m.top.server = {}
    m.top.result = result
end sub
