import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/blockedContent.bs"
import "pkg:/source/utils/config.bs"
import "pkg:/source/utils/parentalControls.bs"

sub init()
    m.top.functionName = "getShuffleEpisodesTask"
end sub

sub getShuffleEpisodesTask()
    data = api.shows.GetEpisodes(m.top.showID, {
        UserId: m.global.session.user.id,
        SortBy: "Random",
        Limit: 200
    })

    if isValid(data) and isValid(data.Items) then data.Items = parentalControls.WithoutBlockedItems(data.Items, blockedContent.SeriesRating(m.top.showID))
    m.top.data = data
end sub
