import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.functionName = "loadCollections"
end sub

sub loadCollections()
    params = {
        userId: m.global.session.user.id,
        IncludeItemTypes: "BoxSet",
        Recursive: true,
        SortBy: "SortName",
        SortOrder: "Ascending",
        Fields: "Overview,ImageTags,BackdropImageTags,PrimaryImageAspectRatio",
        EnableTotalRecordCount: false
    }

    data = api.items.Get(params)

    if not isChainValid(data, "Items") or data.Items.Count() = 0
        m.top.results = []
        return
    end if

    results = []
    for each item in data.Items
        tmp = CreateObject("roSGNode", "CollectionData")
        tmp.json = item
        results.push(tmp)
    end for

    m.top.results = results
end sub
