import "pkg:/source/api/baserequest.bs"
import "pkg:/source/utils/config.bs"

sub init()
    m.top.functionName = "preloadTrickplayImagesTask"
end sub

sub preloadTrickplayImagesTask()
    fs = CreateObject("roFileSystem")

    if m.top.method = "ADD"
        loaded = []
        for each sheet in m.top.sheets
            file = `tmp:/${m.top.videoID}-${sheet}.jpg`
            if not fs.Exists(file)
                APIRequest(`Videos/${m.top.videoID}/Trickplay/${m.top.trickplayWidth}/${sheet}.jpg?ApiKey=${get_user_setting("token")}`).gettofile(file)
            end if
            if fs.Exists(file) then loaded.push(sheet)
        end for
        m.top.loaded = loaded
        return
    end if

    if m.top.method = "REMOVE"
        for each sheet in m.top.sheets
            file = `tmp:/${m.top.videoID}-${sheet}.jpg`
            if fs.Exists(file) then fs.Delete(file)
        end for
    end if
end sub
