import "pkg:/source/api/Image.bs"
import "pkg:/source/enums/ItemType.bs"
import "pkg:/source/utils/misc.bs"

sub setFields()
    if not isValid(m.top.json) then return
    datum = m.top.json

    m.top.id = datum.id
    setPoster()
    m.top.type = ItemType.RECORDING
    m.top.title = datum.name
    m.top.showID = datum.SeriesID
    m.top.seasonID = datum.SeasonID
    m.top.overview = datum.overview
    m.top.favorite = chainLookupReturn(datum, "UserData.IsFavorite", false)
end sub

sub setPoster()
    if isValid(m.top.image)
        m.top.posterURL = m.top.image.url
    else
        m.top.posterURL = metadataPosterURL(m.top.json)
    end if
end sub
