import "pkg:/source/api/Image.bs"
import "pkg:/source/enums/ItemType.bs"

sub setFields()
    if not isValid(m.top.json) then return
    datum = m.top.json

    m.top.id = datum.id
    m.top.title = datum.name
    m.top.overview = datum.overview
    m.top.type = ItemType.SEASON

    setPoster()
end sub

sub setPoster()
    if m.top.image <> invalid
        m.top.posterURL = m.top.image.url
    else
        m.top.posterURL = metadataPosterURL(m.top.json)
    end if

end sub
