import "pkg:/source/utils/misc.bs"

sub init()
    m.posterImage = m.top.findNode("posterImage")
    m.providerText = m.top.findNode("providerText")
end sub

sub itemContentChanged()
    content = m.top.itemContent
    if not isValid(content) then return

    if isValidAndNotEmpty(content.thumbnailUrl)
        m.posterImage.uri = content.thumbnailUrl
    else if isValidAndNotEmpty(content.HDPOSTERURL)
        m.posterImage.uri = content.HDPOSTERURL
    end if

    if isValidAndNotEmpty(content.providerName)
        m.providerText.text = content.providerName
    end if
end sub

sub focusChanged()
end sub
