import "pkg:/source/utils/misc.bs"

sub init()
    m.posterThumb = m.top.findNode("posterThumb")
    m.providerLabel = m.top.findNode("providerLabel")
end sub

sub onItemContentChanged()
    item = m.top.itemContent
    if item = invalid then return

    if isValidAndNotEmpty(item.thumbnailUrl)
        m.posterThumb.uri = item.thumbnailUrl
    end if

    if isValidAndNotEmpty(item.providerName)
        m.providerLabel.text = item.providerName
    end if
end sub
